[nfs]
172.31.24.205 ansible_ssh_user='ec2-user'

[webservers]
172.31.28.235 ansible_ssh_user='ec2-user'
172.31.18.138 ansible_ssh_user='ec2-user'

[db]
172.31.31.158 ansible_ssh_user='ubuntu' 

[lb]
172.31.26.89 ansible_ssh_user='ubuntu'